version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # node_modules をマウント対象から除外
    container_name: vue_frontend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - db_data:/app/quiz_app.db
    container_name: flask_backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
