worker_processes auto;
events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name tk2-206-12684.vs.sakura.ne.jp;

        location / {
            proxy_pass http://vue_frontend:8080;  # Vue.jsフロントエンドにプロキシ
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 443 ssl;
        server_name tk2-206-12684.vs.sakura.ne.jp;

        ssl_certificate /etc/letsencrypt/live/tk2-206-12684.vs.sakura.ne.jp/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/tk2-206-12684.vs.sakura.ne.jp/privkey.pem;

        location / {
            proxy_pass http://vue_frontend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
